api_platform:
    mapping:
        paths: 
            - '%kernel.project_dir%/config/api_platform/resources'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            api_key:
                name: Authorization
                type: header
    title: Symfony API api_platform
    version: 1.0
    show_webby: false