App\Entity\User:
  attributes:
    # encargado de la lectura del recurso
    normalization_context:
      groups: [user_read]
  collectionOperations:
    register:
      method: POST
      path: /users/register
      # llamamos al met invoke de este controller
      controller: App\Api\Action\User\Register
      denormalization_context:
        groups: [user_post]
      # para la interf grafica de swagger
      openapi_context:
        summary: Register a new user

    resend_activation_email:
      method: POST
      path: /users/resend_activation_email
      controller: App\Api\Action\User\ResendActivationEmail
      openapi_context:
        summary: Sends activation email to inactive user
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string

  itemOperations:
    get:
      method: GET

