framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }
        failure_transport: failed
        transports:
            amqp_user:
                dsn: '%env(string:MESSENGER_TRANSPORT_DSN)%'
                serializer: Mailer\Serializer\Messenger\EventSerializer
                retry_strategy:
#                    intenta una vez, si da error al consumir el msj,
#                    lo manda al queue y lo vuelve a intentar. Si se terminan los intentos (max_retries) lo manda
#                    al failure_transport (failed mas abajo)
                    max_retries: 1
                    delay: 1000
                    multiplier: 2
                options:
                    vhost: '%env(string:MESSENGER_VHOST)%'
                    exchange:
                        name: '%env(string:MESSENGER_EXCHANGE)%'
                        type: direct
                    queues:
                        user_queue:
                            binding_keys: [user_queue]
                    auto_setup: true
#           mandamos a una tabla en base de datos los msj fallidos
            failed:
                dsn: 'doctrine://default?queue_name=failed'
        routing:
            # Route your messages to the transports
            'Mailer\Messenger\Message\UserRegisteredMessage': amqp_user
            'Mailer\Messenger\Message\RequestResetPasswordMessage': amqp_user
